output "resource_group_name" {
  description = "Resource group containing all resources."
  value       = azurerm_resource_group.this.name
}

output "sql_server_fqdn" {
  description = "Azure SQL logical server FQDN."
  value       = azurerm_mssql_server.this.fully_qualified_domain_name
}

output "sql_database_name" {
  description = "Azure SQL database name."
  value       = azurerm_mssql_database.this.name
}

output "acr_login_server" {
  description = "ACR login server hostname."
  value       = azurerm_container_registry.this.login_server
}

output "container_app_fqdn" {
  description = "Stable Container App FQDN (not revision-specific)."
  value       = azurerm_container_app.this.ingress[0].fqdn
}

output "static_web_app_default_hostname" {
  description = "Azure-assigned Static Web App hostname."
  value       = azurerm_static_web_app.this.default_host_name
}

output "key_vault_uri" {
  description = "Key Vault URI."
  value       = azurerm_key_vault.this.vault_uri
}

output "apim_gateway_url" {
  description = "APIM gateway URL - call this directly to test APIM -> ACA in isolation, bypassing SWA."
  value       = azurerm_api_management.this.gateway_url
}

output "aca_auth_app_registration_client_id" {
  description = "Client ID of the Entra ID app registration ACA's auth config trusts as its audience."
  value       = azuread_application.aca_auth.client_id
}

output "afd_endpoint_hostname" {
  description = "Front Door endpoint hostname - the single public entry point once origin restriction is applied. Use this, not static_web_app_default_hostname, for all testing."
  value       = azurerm_cdn_frontdoor_endpoint.this.host_name
}

output "afd_front_door_id" {
  description = "This Front Door profile's unique ID (sent as the X-Azure-FDID header on every request it forwards). Required, together with afd_endpoint_hostname above, to fill in item-catalog-ui/public/staticwebapp.config.json for origin restriction - see the README's 'Origin restriction' section. This value is generated by Azure at apply time, not chosen - it cannot be a variable."
  value       = azurerm_cdn_frontdoor_profile.this.resource_guid
}
